# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deno-rest-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deno-rest-api
  template:
    metadata:
      labels:
        app: deno-rest-api
    spec:
      containers:
        - name: deno-rest-api
          image: lanre:latest
          ports:
            - containerPort: 8080